package com.mod;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.Level;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

@Mod(MultiverseMod.MOD_ID)
public class MultiverseMod {
    public static final String MOD_ID = "multiverse";
    public static final Logger LOGGER = LogManager.getLogger(MOD_ID);

    // Claves de las dimensiones del multiverso
    public static final ResourceKey<Level> CONFEDERATE_DIM_KEY = ResourceKey.create(
            Registries.DIMENSION,
            new ResourceLocation(MOD_ID, "confederate_dimension")
    );

    public static final ResourceKey<Level> SOVIET_DIM_KEY = ResourceKey.create(
            Registries.DIMENSION,
            new ResourceLocation(MOD_ID, "soviet_dimension")
    );

    public static final ResourceKey<Level> PUFFER_DIM_KEY = ResourceKey.create(
            Registries.DIMENSION,
            new ResourceLocation(MOD_ID, "puffer_dimension")
    );

    public MultiverseMod() {
        IEventBus modEventBus = FMLJavaModLoadingContext.get().getModEventBus();

        modEventBus.addListener(this::commonSetup);

        MinecraftForge.EVENT_BUS.register(this);
    }

    private void commonSetup(final FMLCommonSetupEvent event) {
        LOGGER.info("MultiverseMod cargado correctamente en Forge.");
    }
}
