plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = '1.0.0'
group = 'com.mod'

base {
    archivesName = 'multiverse'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'DEBUG'
            mods {
                multiverse {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'DEBUG'
            mods {
                multiverse {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/main/generated' }

repositories {
    mavenCentral()
    maven { url = 'https://maven.minecraftforge.net/' }
    maven { url = 'https://maven.parchmentmc.org' }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.2.0'
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            'minecraft_version': '1.20.1', 'minecraft_version_range': '[1.20.1,1.21)',
            'forge_version': '47.2.0', 'forge_version_range': '[47,)',
            'loader_version': '[4,)',
            'mod_id': 'multiverse', 'mod_name': 'Multiverse Mod', 'mod_license': 'All Rights Reserved', 'mod_version': '1.0.0',
            'mod_authors': 'Yo', 'mod_description': 'Un mod de dimensiones para Minecraft Forge.'
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml']) {
        expand replaceProperties
    }
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "multiverse",
                "Specification-Vendor"    : "Yo",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.version,
                "Implementation-Vendor"   : "Yo",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}  
